name: MobTag
version: '${project.version}'
main: me.abood8001.mobtag.MobTag
api-version: '1.21'
author: Abood_8001
description: Displays health tags above mobs with full customization.

softdepend:
  - PlaceholderAPI
  - MythicMobs
  - SimplePets
  - packetevents

commands:
  mobtag:
    description: MobTag main command
    usage: /mobtag reload|toggle
    permission: mobtag.use

permissions:
  mobtag.admin:
    description: Allows use of /mobtag reload
    default: op
  mobtag.toggle:
    description: Allows toggling mob health tags
    default: true
  mobtag.use:
    description: Base permission
    default: true

